
import os, sys
from waflib import Logs

top = '../../../..'
out = 'out'

def options(opt):
    opt.load('compiler_cxx')
    config_options = opt.get_option_group('configure options')
    config_options.add_option('--build-demo',
        action='store_true',
        dest='build_demo',
        help='build the demo application [default: false]')

def configure(conf):
    conf.load('compiler_cxx')
    configure_lib(conf)
    if conf.options.build_demo:
        Logs.warn('DSPFiltersDemo: demo application will also be built.')
        configure_demo(conf)

def configure_lib(conf):
    pass

def configure_demo(conf):
    conf.env['BUILD_DEMO'] = True
    configure_juce(conf)

def configure_juce(conf):
    juce_required_libs=[]
    juce_required_packages=[]
    juce_additional_cxxflags=[]
    
    if os.name.startswith('posix') and not sys.platform.startswith('darwin'):
        juce_required_libs+=['dl', 'pthread', 'rt']
        juce_required_packages+=['freetype2', 'gl', 'glu', 'x11', 'xinerama', 'alsa', 'xext']
        # A really ugly hack to make the amalgam compile under g++ 4.7,
        # a better solution could be provided by JUCE upstream itself.
        juce_additional_cxxflags+=['-include', 'unistd.h']
    else:
        # TODO: add Darwin and non-POSIX dependency checks
        conf.fatal('DSPFiltersDemo: Building DSPFiltersDemo with waf is currently only possible on'
            ' POSIX systems with X11.')

    for l in juce_required_libs:
        conf.check(
            lib=l,
            uselib_store=l)
    for pkg in juce_required_packages:
        conf.check_cfg(
            package=pkg,
            uselib_store=pkg,
            args=['--cflags', '--libs'])
    conf.env.append_value('JUCE_USELIBS', juce_required_libs)
    conf.env.append_value('JUCE_USELIBS', juce_required_packages)
    conf.env.append_value('JUCE_ADDITIONAL_CXXFLAGS', juce_additional_cxxflags)


def build(bld):
    build_lib(bld)
    if bld.env['BUILD_DEMO']:
        build_demo(bld)

def build_lib(bld):
    dspfilters_include_dir = bld.path.find_dir('../../include')
    bld.install_files('${PREFIX}/include',
        dspfilters_include_dir.ant_glob('**/*.h'),
        cwd=dspfilters_include_dir,
        relative_trick=True)
    bld.shlib(
        source=bld.path.parent.parent.ant_glob('source/*.cpp'),
        includes='../../include',
        target='DSPFilters')

def build_demo(bld):
    build_juce(bld)
    bld.program(
        source=bld.path.parent.parent.parent.ant_glob('DSPFiltersDemo/source/*.cpp'),
        includes=['../../../DSPFiltersDemo/source', '../../include', '../../../JuceAmalgam'],
        use=bld.env['JUCE_USELIBS'] + ['JuceAmalgam', 'DSPFilters'],
        target='DSPFiltersDemo')

def build_juce(bld):
    bld.stlib(
        source=bld.path.parent.parent.parent.ant_glob('JuceAmalgam/*.cpp'),
        includes='../../../JuceAmalgam',
        use=bld.env['JUCE_USELIBS'],
        cxxflags=bld.env['JUCE_ADDITIONAL_CXXFLAGS'],
        target='JuceAmalgam')

# vim: syntax=python
